variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  JDK17_IMAGE: "maven:3.9.5-eclipse-temurin-17"
  JDK21_IMAGE: "maven:3.9.5-eclipse-temurin-21"

cache:
  paths:
    - .m2/repository

test:jdk17:
  image: $JDK17_IMAGE
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report'
  artifacts:
    when: always
    paths:
      - target/site/jacoco/jacoco.xml
      - target/site/jacoco/index.html
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  only:
    - branches

test:jdk21:
  image: $JDK21_IMAGE
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS clean test'
  only:
    - branches

coverage:jdk17:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.9
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - 'python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml'
    - 'python /opt/source2filename.py target/site/cobertura.xml'
    - 'cat target/site/jacoco/index.html'
  needs: ["test:jdk17"]
  dependencies:
    - test:jdk17
  artifacts:
    reports:
      coverage_report:
        path: target/site/cobertura.xml
        coverage_format: cobertura
  except:
    - tags

lint:jdk17:
  image: $JDK17_IMAGE
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS clean checkstyle:check'
  only:
    - branches

deploy:jdk17:
  image: $JDK17_IMAGE
  stage: deploy
  script:
    - 'cp $SETTINGS_XML ~/.m2/settings.xml'
    - 'mvn $MAVEN_CLI_OPTS clean deploy -DskipTests'
  only:
    - tags

stages:
  - test
  - visualize
  - build
  - deploy
