name: Maven Checkstyle

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17 ]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'checkstyle-check'
          tool_name: 'reviewdog'
